var message = "Hello typescript";
var firstyName = "Muhammad Zeeshan ";
var laastName = "Latif";
var fullName = firstyName + laastName;
var sentence = "My name is Zeeshan and I am Hafiz";
var sentenceLength = sentence.length;
var upperCaseText = sentence.toUpperCase();
var lowerCaseText = sentence.toLowerCase();
console.log(upperCaseText);
console.log(lowerCaseText);
